# Generated by Django 4.0.5 on 2023-05-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_capacity_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='store-pics/default.jpg', upload_to='store-pics'),
        ),
    ]
