# Generated by Django 4.1.5 on 2023-03-22 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_rating', models.CharField(max_length=10)),
                ('product_category', models.CharField(max_length=50)),
                ('product_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=36)),
                ('author', models.CharField(max_length=255)),
                ('stars', models.CharField(max_length=255)),
                ('recommendation', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField()),
                ('date_p', models.DateTimeField()),
                ('date_b', models.DateTimeField()),
                ('days_used', models.IntegerField()),
                ('t_up', models.IntegerField()),
                ('t_down', models.IntegerField()),
                ('opinion', models.TextField()),
                ('pos_features', models.JSONField()),
                ('neg_features', models.JSONField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_reviews', to='main.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(related_name='reviews', to='main.review'),
        ),
    ]
