# Generated by Django 4.0.5 on 2023-03-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.IntegerField()),
                ('product_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=255)),
                ('review_id', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('is_recomended', models.BooleanField()),
                ('is_verified', models.BooleanField()),
                ('stars', models.CharField(max_length=5)),
                ('date_p', models.DateTimeField()),
                ('date_b', models.DateTimeField()),
                ('t_up', models.IntegerField()),
                ('t_down', models.IntegerField()),
                ('opinion', models.TextField()),
                ('pos_features', models.JSONField(default=list)),
                ('neg_features', models.JSONField(default=list)),
            ],
        ),
    ]
