# Generated by Django 4.1.5 on 2023-03-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recommendation',
            field=models.CharField(max_length=255),
        ),
    ]
