# Generated by Django 4.1.5 on 2023-03-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_reviews_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_name',
        ),
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='products',
            name='reviews',
        ),
        migrations.AddField(
            model_name='products',
            name='reviews',
            field=models.ManyToManyField(to='main.reviews'),
        ),
    ]
