# Generated by Django 4.1.5 on 2023-03-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_review_delete_products_delete_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviewss',
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(related_name='products_reviews', to='main.review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_reviews', to='main.product'),
        ),
    ]
